TSE Review for User interface Branch
hillarioh/tic-tac-toe pull request #2
Opened 2020-05-01 14:28 UTC by Calvinoea

Hello,

We (Hillario and I) are making a request for your review of our user interface milestone submission as part of the Ruby curriculum administered by Microverse. 

The features include:

- Display prompts for users (hint: puts/print)
- Collection of user input 
- Basic mock flow of the game

Thanks for your review!

2020-05-02 15:36 UTC, whiz25 requested changes
## Nice one :+1: 
Your game logic is almost done. We need to fix a few things before it's ready for implementation.
- [ ] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
An example of a variable terminated while loop.
```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move
  
  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```
- [ ] add logic for draw
- [ ] enable stickler in this repo and make sure all test cases pass

### Martin Afani

2020-05-02 15:39 UTC, whiz25 commented on bin/main
> +puts new_game
- [ ] why three of this?

2020-05-02 15:39 UTC, whiz25 commented on bin/main
> +end
- [ ] you need a loop to continuously repeat this step until there is a winner or a draw

2020-05-02 15:39 UTC, whiz25 commented on bin/main
> +puts 'You win, player one'
- [ ] when does someone win?

2020-05-04 10:48 UTC, whiz25 requested changes
## Nice Progress :+1: 
You have made some changes as suggested. But we need to fix a few things before we can merge this PR.

- [ ] check my comments for suggestions

### Martin Afani

2020-05-04 10:52 UTC, whiz25 commented on bin/main.rb
> +end
- use a variable to terminate the loop.
- this should not be complex. you can even use just comments to show you thought process.
- for example,
```ruby
game_on = true
while game_on
# let players take turn until there is a winner
if winner
# tell which player won and end game
end
game_on = false
end
```

2020-05-04 23:28 UTC, majovanilla approved these changes
Hi team!!

Good job :heavy_check_mark: implementing the required changes!! :star: 

Your project is ready for the next stage!! :100:

### Milestone 2 approved. Please merge and continue.


If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-05-05 01:49 UTC, merged